### ISSUE TITLE
`f-string` support for `python-mode`

### ISSUE THREAD

**Issue by liebkne** [manateelazycat/grammatical-edit#8]
Currently one can not pair `{}`, `[]` or `()` inside [f-string](https://www.python.org/dev/peps/pep-0498/) in Python. e.g. the bracket inside`f"{"` or `f'{'` is not auto paired. It would be nice to have support for this.

**Comment by manateelazycat** [comment]
We won't insert any pair in string or comment, it's a feature, reason I have post in https://github.com/manateelazycat/grammatical-edit/issues/7#issuecomment-991447507

We don't know when need insert or remove pair in string, because we can have any number [ or { in string, example we need write regexp string in Python to match special string, "^{abc", we can't insert pair automatically in this situation.
